module.exports = {
  apps: [
    {
      name: 'jianmu-hub',
      script: 'hub.mjs',
      cwd: 'D:/workspace/ai/research/xiheAi/xihe-jianmu-ipc',
      interpreter: 'node',
      env: {},
      env_file: '.env',
      error_file: 'D:/workspace/ai/research/xiheAi/xihe-jianmu-ipc/data/jianmu-hub-error.log',
      out_file: 'D:/workspace/ai/research/xiheAi/xihe-jianmu-ipc/data/jianmu-hub-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      max_restarts: 50,
      restart_delay: 3000,
      watch: false,
    },
    {
      name: 'feishu-bridge',
      script: 'feishu-bridge.mjs',
      cwd: 'D:/workspace/ai/research/xiheAi/xihe-jianmu-ipc',
      interpreter: 'node',
      error_file: 'D:/workspace/ai/research/xiheAi/xihe-jianmu-ipc/data/feishu-bridge-error.log',
      out_file: 'D:/workspace/ai/research/xiheAi/xihe-jianmu-ipc/data/feishu-bridge-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      watch: false,
    },
  ],
};
